# Generated by Django 4.1.2 on 2022-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('Username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
