# Generated by Django 4.1.2 on 2022-11-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
