# Generated by Django 4.1.2 on 2022-11-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='info',
        ),
    ]
