# Generated by Django 4.1.2 on 2022-11-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_rename_userinfo_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='info',
        ),
    ]
