# Generated by Django 4.1.2 on 2022-11-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_userinformation_delete_userinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinformation',
            table=None,
        ),
    ]
