# Generated by Django 4.1.2 on 2022-11-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_alter_userinformation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinformation',
            table='UserInformation',
        ),
    ]
